### ISSUE TITLE
Job Interview Checklist - Aiden Huynh

### ISSUE THREAD

**Issue by aidenhuynh** [aidenhuynh/Epic_CSA#12]
## Checklist
- [x] LinkedIn Preview
- [x] Key interests and how coding aligns with interests of employer
- [x] Showing how past projects relate to employer's interest
- [x] Teamwork methodologies (explain scrum and agile), show how you are a collaborator
- [x] Videos and links of past projects
- [x] Show how I've used full stack (do this in a past project)
- [x] Show blog and have a useful index page
- [x] GitHub analytics
- [x] Showcase events N@TM
- [x] Demo two projects, 1 minute each
- [x] Unique qualification

## Organization
1. LinkedIn
2. Key Interests (collaboration, teamwork, education)
3. Teamwork methodologies
4. Unique qualification, interest in education, show blog of dark mode stuff
5. Past projects all linked on index of blog (My past projects) and maybe analytics
6. Classroom jukebox fun thing that shows interest in helping community, leads to nighthawk resources
7. Nighthawk resources full stack in table gen and class generation
8. Another outlet I use to teach compsci is N@tm
